### ISSUE TITLE
Clients do not gracefully handle server faults

### ISSUE THREAD

**Issue by mattyokan** [WorldQL/mammoth#16]
When the server runs into halting exceptions, clients do not gracefully handle reconnection.

# Video

Check discord: https://discord.com/channels/701873003679449108/701876824732598414/885877307665952809

# Expected Behavior

When the server is restarted, existing clients should not experience desync.

# Actual Behavior

After server failure, clients remain out-of-sync, leading to strange behavior.

**Comment by Jaxkr** [comment]
The Heartbeat system in the upcoming rewrite of WorldQL has fixed this bug. Thanks for your report.
