### ISSUE TITLE
[Client] Players do not immediately broadcast their presence on join.

### ISSUE THREAD

**Issue by mattyokan** [WorldQL/mammoth#17]
# Expected Behavior

When a player joins on an instance, they should be visible on other instances.

# Actual Behavior

Players only appear after rotating their head or moving.

# Video

In discord: https://discord.com/channels/701873003679449108/701876824732598414/885879554017755206

**Comment by Jaxkr** [comment]
This has been fixed in the upcoming 1.18 release.
